### ISSUE TITLE
Consider including the hash algoirthm in our ref encoding.

### ISSUE THREAD

**Issue by zenhack** [bobg/bs#4]
Right now we're hard-coding use of sha256, which is fine, but perhaps someday attacks will be found against sha256 and it will be deemed too weak to be safe. Perhaps we should format refs in a way that encodes the hash algorithm used, so that if we ever need to change the algorithm it is easier to do so.

**Comment by bobg** [comment]
I don't know, we now have an attack against sha1 and that hasn't stopped git from using it. This feels to me very much in the categories of YAGNI and "we'll have bigger problems to deal with when and if that happens," so I'll be happy to have a [flag day](http://catb.org/jargon/html/F/flag-day.html) in that case, forcing some sort of migration, and not worrying about it until then.

Closing for now.

**Comment by zenhack** [comment]
So, I have a perkeep data store that's >1TiB in on-disk size; upgrading that on a flag day sounds painful at best, and that's something that's within the scope of one hard drive (well, 2 for redundancy) owned by an individual; one-shot migrations of data don't work over a certain size.

Fwiw, git is still using sha1 in part *because* upgrading is a pain. [They're actively working on it][1], but the fact that hashes aren't tagged with the algorithm is a significant source of complexity for their migration.

...And in the meantime, the fact that git uses an insecure hash makes it inappropriate for some use cases that I am interested in: it means you basically can't store anything supplied by untrusted users. Maybe not a showstopper for an scm where you ought to be hand-auditing everything people send you anyway (basically byte-for-byte, since it's typically plain text), but I do bulk backups of my system with perkeep, and I don't want to have to worry about whether somebody could trash my data by emailing me a PDF with a block that collides with something I care about.

By contrast, perkeep moved from sha1 to sha224 without much fuss, since they already had the digests prefixed.

But I guess that's the beauty of using something like pb or capnp: if we use a pb message type or the like for refs (instead of a bare bytes field) then we can always just add a field for this later, if and when we discover we need to migrate.
